development:
  adapter: postgresql
  encoding: unicode
  database: aprilandjakedata_development
  pool: 5
  username: aprilandjakedata
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: aprilandjakedata_test
  pool: 5
  username: aprilandjakedata
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: aprilandjakedata_production
  pool: 5
  username: aprilandjakedata
  password: